### ISSUE TITLE
[fixed-pipeline] remove glBegin/glEnd pairs

### ISSUE THREAD

**Issue by gcask** [daid/EmptyEpsilon#1319]
- [x]  3D reticule (#1314)
- [x] Starbox (#1313)
- [x]  space objects (black holes, planets, explosions...) (#1303) 
- [x] Particles (#1310)
- [x] spacedust (#1329)
- [x] nebulas game info (#1335, #1331)

Debug features:
- [x] collision boxes (viewport3d) (#1332)
- [x] engine emitters (rotationModelView) (#1332)
